[Eth]
NetworkId = 5000  # Unique network ID for NeuraChain
SyncMode = "full"
EthDiscoveryURLs = []
SnapDiscoveryURLs = []
NoPruning = false
NoPrefetch = false
TxLookupLimit = 1000000  # Reduce to 1 million for NeuraChain
TransactionHistory = 1000000
StateHistory = 90000
DatabaseCache = 512
DatabaseFreezer = ""
TrieCleanCache = 154
TrieDirtyCache = 256
TrieTimeout = 3600000000000
SnapshotCache = 102
Preimages = false
FilterLogCacheSize = 32
EnablePreimageRecording = false
VMTrace = ""
VMTraceJsonConfig = ""
RPCGasCap = 50000000
RPCEVMTimeout = 5000000000
RPCTxFeeCap = 1e+00

[Eth.Miner]
GasCeil = 30000000
GasPrice = 1000000000

[Eth.TxPool]
Locals = []
NoLocals = false
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1
PriceBump = 10
AccountSlots = 16
GlobalSlots = 5120
AccountQueue = 64
GlobalQueue = 1024
Lifetime = 10800000000000

[Eth.BlobPool]
Datadir = "blobpool"
Datacap = 2684354560
PriceBump = 100

[Eth.GPO]
Blocks = 20
Percentile = 60
MaxHeaderHistory = 1024
MaxBlockHistory = 1024
MaxPrice = 100000000000
IgnorePrice = 2

[Node]
DataDir = "/root/.neuraChain"
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
HTTPPort = 8645
HTTPVirtualHosts = ["*"]
HTTPModules = ["net", "web3", "eth"]
AuthAddr = "localhost"
AuthPort = 8651
AuthVirtualHosts = ["localhost"]
WSHost = ""
WSPort = 8646
WSModules = ["net", "web3", "eth"]
GraphQLVirtualHosts = ["localhost"]
BatchRequestLimit = 1000
BatchResponseMaxSize = 25000000

[Node.P2P]
MaxPeers = 100
NoDiscovery = false
DiscoveryV4 = true
DiscoveryV5 = true
BootstrapNodes = ["enode://1cbb200fa7b74edcc9cb86667701efa4afa05d84065f8d854418ed1b2352a4be79c3b466aa7ce265105fc2d8b8a7ee429d1cfb697c57d47980add1882820ebc5@147.79.68.142:30303"]
BootstrapNodesV5 = []
StaticNodes = []
TrustedNodes = []
ListenAddr = ":31303"
DiscAddr = ""
EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
ReadHeaderTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000

[Metrics]
HTTP = "127.0.0.1"
Port = 6160
InfluxDBEndpoint = "http://localhost:8086"
InfluxDBDatabase = "neuraChain"
InfluxDBUsername = "test"
InfluxDBPassword = "test"
InfluxDBTags = "host=localhost"
InfluxDBToken = "test"
InfluxDBBucket = "neuraChain"
InfluxDBOrganization = "neuraChain"
